# Created by tools/Update-WingetManifest.ps1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Morfyuum.AtlayaView
PackageVersion: 2.1.2
InstallerType: inno
Scope: machine
InstallModes:
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART"
  SilentWithProgress: "/SILENT /SUPPRESSMSGBOXES /NORESTART"
Installers:
  - Architecture: x64
    InstallerUrl: https://atlaya.capecter.com/downloads/atlayaview/2.1.2/AtlayaView-Setup-2.1.2-full.exe
    InstallerSha256: F0F6583DB89DECB6644E34D87BD400DCAFF12D8A1EF04B4341B05B2610C61433
    ProductCode: "{38EAC974-2DF5-4D63-A335-ECE4E477537E}_is1"
    AppsAndFeaturesEntries:
      - DisplayName: "AtlayaView"
        Publisher: "Atlaya"
ManifestType: installer
ManifestVersion: 1.12.0
