# Created by tools/Update-WingetManifest.ps1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Morfyuum.AtlayaView.FxDependent
PackageVersion: 2.1.2
InstallerType: inno
Scope: machine
InstallModes:
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART"
  SilentWithProgress: "/SILENT /SUPPRESSMSGBOXES /NORESTART"
Installers:
  - Architecture: x64
    InstallerUrl: https://atlaya.capecter.com/downloads/atlayaview/2.1.2/AtlayaView-Setup-2.1.2-fx.exe
    InstallerSha256: 0071516BE89B782F407F0842835BC290C1D382A2C25323B4CCEC455772D89CDD
    ProductCode: "{D94DF165-53AB-424B-8539-2411D56612E4}_is1"
    AppsAndFeaturesEntries:
      - DisplayName: "AtlayaView (ohne .NET-Runtime)"
        Publisher: "Atlaya"
ManifestType: installer
ManifestVersion: 1.12.0
